### ISSUE TITLE
Xp-Bot系コマンドの実行チャンネル変更への対応

### ISSUE THREAD

**Issue by foo87b** [xpjp/xpfiat-bot#103]
### 実現したいこと
コマンド毎に実行する部屋が変更され、各チャンネル名も変更となります。
お手数おかけしますが対応をお願いします。

 Command  |     Channel ID     | Channel Name
--------- | ------------------ | ------------
,register | 390074030834712576 | #xpbot_register
,balance  | 375532870376357889 | #xpbot_balance
,deposit  | 390058691845554177 | #xpbot_deposit_withdraw
,withdraw | 390058691845554177 | #xpbot_deposit_withdraw
,rain     | 379064989270540300 | #xpbot_rain_tip
,tip      | 379064989270540300 | #xpbot_rain_tip

### ゴール
変更が完了したらcloseをお願いします。

### 相談したいこと
もしよければ、チャンネルはIDでも指定できると助かります。

**Comment by mc-chinju** [comment]
えーと、警告文を出すチャンネルの制御のことですよね？
コマンドとチャンネルが 1:1 対応になったので、それ以外の room で呼ばれた場合に警告文出すようにすればいいでしょうか？

**Comment by foo87b** [comment]
はい、警告文を出すチャンネルの制御です。
tipとrainは上記の表以外でも実行可能な部屋がありますが、それ以外のコマンドに関しては上記の部屋限定で運用したいと考えております。

**Comment by mc-chinju** [comment]
> tipとrainは上記の表以外でも実行可能な部屋がありますが、それ以外のコマンドに関しては上記の部屋限定で運用したいと考えております。

む、 `tip` と `rain` も上表以外の部屋だと警告文でるようにしてしまったんですが、外しておいたほうがいいですかね。
コマンド呼び出しで切り替えしたくなりますね。
