### ISSUE TITLE
テストを書きたい

### ISSUE THREAD

**Issue by rockymanobi** [xpjp/xpfiat-bot#12]
今は希望だけ

discard bot のプロジェクトでテストが書かれてるやつを参考にしたい欲求があります

**Comment by Asuforce** [comment]
#8 と関連しそうですね

> discard bot のプロジェクト

見てみたいので url いただければと思います〜

**Comment by rockymanobi** [comment]
色々探してますが、OPENなのはサンプル系が多くて、テストまでちゃんと書いてあるのはあんまりないですね。試行錯誤。

**Comment by Asuforce** [comment]
わかりました！
ci の導入と一緒に rspec 入れようかなと思ってました。少し待った方がいいですかね？

**Comment by rockymanobi** [comment]
@Asuforce 
rspec お願いします!!
悩んでるのはdiscord周りのテストの書き方レベルなので、rspec入れることについては100% agreeです :)

**Comment by Asuforce** [comment]
ありがとうございます！では CI 進めます！

>悩んでるのはdiscord周りのテストの書き方レベル

これ僕も考えていたのですが、レスポンスは専用のクラス作って、メソッド定義してやれば単体テストはできるかなと思いました 😄

**Comment by toshikidoi** [comment]
「CIでRSpec回す」、「テストはとりあえずレスポンスの単体テスト」、諸々賛成です👍

**Comment by rockymanobi** [comment]
ではそんな方針で。
とりあえず #8 でrspec入った段階でCloseしましょう

**Comment by Asuforce** [comment]
テストを書く準備はできたのでクローズ
