### ISSUE TITLE
GithubとCIの結果等をdiscordチャネルに通知する

### ISSUE THREAD

**Issue by rockymanobi** [xpjp/xpfiat-bot#13]
* チャネルは流石にprivateが良さそう
* #8 にも関連

できれば本番エラーも気付けるように（これは別だけど）したい

**Comment by toshikidoi** [comment]
たしかに、今後連携する物が増えてくと、バンバン通知来ちゃいそうなので、privateな通知用チャンネルを用意した方がベターぽいですね。

**Comment by toshikidoi** [comment]
テスト

**Comment by toshikidoi** [comment]
テスト

**Comment by toshikidoi** [comment]
こちら、通知は`xpjp_lab_notification`というチャンネルに流すことになりました。
今後色々増えたら、また考えましょうか。

**Comment by Asuforce** [comment]
この issue のゴールはひとまず GitHub と CI を設定するところまでやっていきましょう！

**Comment by Asuforce** [comment]
GitHub, Travis 共に通知するようにできたのでクローズ
