### ISSUE TITLE
みんなでモンスターを倒す？

### ISSUE THREAD

**Issue by axis06** [xpjp/xpfiat-bot#18]
### 実現したいこと

xpに合わせて攻撃力が決まる
（クリティカルヒットなどもある）

倒したあとそのモンスターが持っていたxpは試合に攻撃した人の中で山分け。
一定時間以内に倒せないと流れる。

### ゴール

モンスター発生。一定時間で倒す。

### 相談したいこと

うまくxpコインが回る仕組みづくりをする方法はないのか

**Comment by ett126** [comment]
私も似たようなことを考えてました！！

botサーバとは別にPosする環境を用意して、stakeしたら敵がポップ。みんなで倒してそのxpを山分け。

stake量でボス出現、とか。。

ただ、stakeするための原資どうすんだって話ですが
アイデアとして…
