### ISSUE TITLE
雑談系Bot

### ISSUE THREAD

**Issue by Diaboro87** [xpjp/xpfiat-bot#19]
### 実現したいこと

みんなのメッセージを集めて、解析して発話するBotを作る。
所謂しゅうまい君てきな。

### ゴール

ディスコ内のメッセージを収集し、適度に発話するBotを作る

### 相談したいこと

とりあえず、Twitterからツイートを取得して、ゴニョゴニョして、発話するBotまではあるので、ディスコからメッセージを取得するところだけ作れば動くかなと(安易)

相談したいこととしてはこのアプリ、収集した発言を蓄積するDBが必要なのでどこに用意するかな？ってところですかね。

**Comment by soyanakagawa** [comment]
こういうのでもいいですね。聞くところによると、ある程度文脈よんで発言してくれるらしいです。
https://dev.smt.docomo.ne.jp/?p=docs.api.page&api_name=dialogue&p_name=api_reference

**Comment by Diaboro87** [comment]
ドコマルちゃんでしたっけ？最初の導入にはいいかもしれません。これ採用。作ります。

**Comment by Diaboro87** [comment]
デプロイされたのでクローズ
