### ISSUE TITLE
サーバを有効活用したい

### ISSUE THREAD

**Issue by Asuforce** [xpjp/xpfiat-bot#20]
### 実現したいこと

@p-suke が作成してくれたサーバがあるので有効活用したい

### ゴール

- サーバを何に使うか決める

### 相談したいこと

今の所、新規 bot 用にするのか xpfiat-bot の staging にするのかどうしようかなぁという思いです。
挙げたやつ以外の使い道を議論していただいても構いません。有効活用しましょう！

**Comment by Diaboro87** [comment]
1. 降雨量Botのために、チャット(rainコマンド)を蓄積しておきたい。(いつ、いくら)
2. 自動つぶやきBotのために、APIサーバーとして利用したい。

とりあえず２つ。

**Comment by Asuforce** [comment]
@Diaboro87 このサーバって今何に使われていますか？

**Comment by Diaboro87** [comment]
形態素解析用のAPIを置くアプリケーションサーバーと、解析結果を置くデータベースサーバですね。
どちらもまだ稼動前です。

**Comment by Asuforce** [comment]
わかりました！ありがとうございます。
何かお手伝いできることがあれば言っていただければと思います 😊
