### ISSUE TITLE
数字３桁ごとにカンマを挿入する

### ISSUE THREAD

**Issue by soh92** [xpjp/xpfiat-bot#21]
### 実現したいこと

Botから出力される数値を見やすくする為にカンマを入れる

### ゴール

３桁ごとにカンマが入る（小数点以下は入らない）

### 相談したいこと

一度文字列にして、カンマを挿入するつもりですが、小数点以下が入ってもカンマを挿入できる方法（例えばこんな感じ->1,234.456)があれば教えてください。

**Comment by Asuforce** [comment]
個人的には @Diaboro87 さんの後者の提案がいいですね。理由としては Activerecord をこれのためだけに入れるのは大きすぎるかなという思いです。

**Comment by Diaboro87** [comment]
あとはこれとか？
https://www.mk-mode.com/octopress/2012/06/22/22002053/

正規表現でやるのがベターかも。
正規表現のお試しサイト
http://rubular.com/

**Comment by soh92** [comment]
今は正規表現でやってますね。現在出力される多くの数値には対応できますが、1234.456といった小数点以下を含む場合をどうしようか悩んでます。これも正規表現でいけますかね。

**Comment by Diaboro87** [comment]
JavaScriptですけど、ロジック的にはこれで取れそうです。
https://st40.xyz/one-run/article/347/

**Comment by soh92** [comment]
ありがとうございます。参考にして今のメソッド書き換えてみます。

**Comment by soh92** [comment]
できました。感謝です
