### ISSUE TITLE
XPの時価総額を呟くbot

### ISSUE THREAD

**Issue by mario2331** [xpjp/xpfiat-bot#31]
### 実現したいこと

XPの時価総額と現在の順位・次の順位を抜くまでの時価総額量を
返すbotを作成（discordとtwitter両方）

### ゴール
discordとtwitterbotの実装
(issue を close する条件を定義します)

### 相談したいこと
issue化しました。
RUBYと既存のコードを勉強しながらの実装なので、たくさん相談させていただくかと思いますが、
よろしくお願いいたします。

**Comment by Diaboro87** [comment]
かってにアサインしてしまったんですけど、このイシュー、ディスコとTwitterでイシュー分けたほうがいいかも。
