### ISSUE TITLE
?helpコマンドの見やすさ改善(コードレベルの話)

### ISSUE THREAD

**Issue by Diaboro87** [xpjp/xpfiat-bot#32]
### 実現したいこと

とりあえず、1行で書かれてるので、何行かに分ける。
あとは、まだ未記載のコマンドは追加する。

### ゴール

「実現したいことの達成」

### 相談したいこと

隠しコマンドってどれ？

**Comment by Diaboro87** [comment]
ヘルプコマンドへの追記と、軽いリファクタリングを行いました。
レビューお願いします

**Comment by Asuforce** [comment]
この粒度だと、プルリクでわかるので issue じゃなくても OKです 👍 
多くの人と議論が必要そう、実装がまだ思いつかないけどけっこう大きな機能を開発するって時に issue を立てると便利だと思います〜
あと In Review ラベルはプルリに使うやつかなという認識です。
重箱の隅を突くようなことばかり言ってすいません 🙏

**Comment by Diaboro87** [comment]
なるほど。
ちょっといじったんで見といて！議論とかいらないでしょ！
みたいなやつは作ってプルリク出しちゃえばいいんですね。了解です。
とりあえず、タスク上げてからかなと勝手に。

**Comment by mc-chinju** [comment]
Fixed by https://github.com/xpjp/xpfiat-bot/pull/33
