### ISSUE TITLE
TOKENとCLIENT_IDの設定をコード修正なしに開発者用のものを使えるようにしたい

### ISSUE THREAD

**Issue by rockymanobi** [xpjp/xpfiat-bot#4]
**良い実行案募集中です**

https://github.com/xpjp/xpfiat-bot/blob/master/xp_fiat.rb#L6

開発時には各自個々の開発用TokenとClientIdを利用するようになっていますが、コミット時に戻し忘れる、間違えて開発者のクレデンシャル情報をコードに書き込んでしまう、という事故が起こりやすいのでなんとかしたい。。

## 実現案

この手のrubyコードの開発はあまりやらないのでふわっとしていますが、パッと思いつくのは以下です。
なんとなく、Aが色々な環境に出せるのでセオリーな気がします。

* A. 環境変数を使うようにする
  * 本番へのデプロイも楽になる（はず）
  * 起動は若干複雑になる ex: `TOKEN=xxxxx CLIENT_ID=XXXX bundle exec ruby xp_fiat.rb` 
    * ので、上記起動スクリプトのgeneratorのコマンドを用意してあげて、そこで生成されるファイル名をgitignoreに入れておく（これで間違ってコミットされない）
    * (そこまで最初はやんなくて良さそう）
* B. 環境別の設定ファイルを用意する
  * 結局事故りそう... publicリポジトリには向かないかも

**Comment by toshikidoi** [comment]
A案かなー。

https://qiita.com/ogawatti/items/e1e612b793a3d51978cc

チャットで出てたのが、これです。↑

**Comment by rockymanobi** [comment]
おお、いいですね。コレで行きたいですね。

のレベルだと意見別れないと思いますが、この辺の決断どうするのかはガイドラインいるかもですね~

**Comment by Asuforce** [comment]
dotenv 入れたので、解決かなと思います。クローズしますね〜（議論が足りなければ再度オープンで
