### ISSUE TITLE
デプロイを自動化する

### ISSUE THREAD

**Issue by Asuforce** [xpjp/xpfiat-bot#41]
### 実現したいこと

現状のデプロイは @p-suke さんしかできない状態なので、属人性が高くなっています。
これを自動化することで運用の負担を減らしたいです。

### ゴール

- master のデプロイがある程度のメンバー(Owner など)でできるようにする

### 相談したいこと

CI からできないかなと考えましたが、サーバの情報を丸々公開することになるのであまりよくなさそうです。そこでサーバが master の更新を検知してファイルを更新するというのができないか考えています。
何かアイディアがありましたら意見いただきたいです。

**Comment by torii** [comment]
まずはお手軽な方法で、cronあたりで定期的にgitの差分チェック（またはCIのテスト通過後にping）して、pullした後にsuperviseっぽいやつ経由で再起動という感じはいかがでしょう。

具体的な方法は、今のBOTが動いているサーバ環境に合わせることになると思うので調査してからまずは簡単な方法で実現できたらいいなと考えます。

**Comment by Asuforce** [comment]
無駄に consul とか妄想してしまっていたので、大変ありがたい意見です。
僕も cron からスタートでも良さそうだなと思いました。

@p-suke 
現状はサーバにどうやってデプロイしてるか教えていただけますでしょうか？

**Comment by mc-chinju** [comment]
@p-suke 
こちらですが、EC2 あたりで master を git pull して ruby を background で動かしているだけですかね？
デプロイというか、git pull して再起動してるだけみたいな。

**Comment by p-suke** [comment]
vultrのVPSで動いています。
ローカルでgit pullして必要なファイルをSFTPでアップして再起動と非効率なことしてました。。。

**Comment by Asuforce** [comment]
master マージで CI からデプロイすると楽だなと思ったので、やりたいですね
