### ISSUE TITLE
コードの体裁を整えたい

### ISSUE THREAD

**Issue by Asuforce** [xpjp/xpfiat-bot#66]
### 実現したいこと

機能が増えてきたので、ワンファイルだとコンフリクトが増え開発スピードの低下が発生しそうな状態になりました。適切なクラス分け、ファイル分割などを実施して管理しやすくしたいです。

### ゴール

機能に応じたファイル分割が完了する

### 相談したいこと

クラス分けもしたいですが、ファイル分割からやるのがいいかなと思ってます

**Comment by harigel** [comment]
ぜひ！

API呼び出し部分、レート計算は別モジュール化したいです。
あとコマンドは１コマンド（機能？）１ファイルにしちゃってもいいと思ってますがやり過ぎですかね…

**Comment by Asuforce** [comment]
賛同いただきありがとうございます！

> あとコマンドは１コマンド（機能？）１ファイルにしちゃってもいいと思ってますがやり過ぎですかね…

いや、やりすぎではないと思います。
その方が自由に開発していただける気がするからです。

**Comment by mc-chinju** [comment]
こちらやりたいなーと思ってました。もう着手されてます？

**Comment by harigel** [comment]
私はまだ着手してないです。構成詰めてからのほうがいいかなと。

なんとなく

```
├── bot_controller.rb
├── actions
│   ├── commands # この下にコマンドを並べる
│   │   ├── xp_jpy.rb
│   │   └── xp_doge.rb
│   └── reactions # この下にリアクション系を並べる。パトロールもここ？
│       ├── dawa.rb
│       └── soon.rb
├── services # 外部連携が必要なものはここにまとめる
│   └── api
│       ├── coinexchange.rb
│       └── xxx.rb
├── schedulers # 定期処理したいものはこちら
│   └── status_updater.rb
├── urils # 各種ユーティリティ
│   └── rate_calculator.rb
```

こんな感じを想像してました。

botインスタンスの取り回しが悩みどころです…
とりあえず考えてるのは、bot_controllerでbot初期化してコマンドモジュール等をincludeすると
各コマンドモジュールに@botが生える、というようなものです。

ruby的には普通こんな感じにするとか、ここいけてないとか、ご意見いただきたいです。

**Comment by Asuforce** [comment]
素晴らしい...
とりあえず `lib` 以下にファイル生やそうかなしか考えてなかったので感動してます。
上記なら分業できそうな感じですね〜

> ruby的には普通こんな感じにする

ref: https://github.com/sparklemotion/nokogiri
前述の通り、 `lib` 以下に展開していくといいかなと考えています
大体、Gem ファイルのディレクトリ構成が一般的なのかなと思います

**Comment by mc-chinju** [comment]
ディレクトリ構造素晴らしいですね...！ Android とか確かにこんな感じによくしてました。

@Asuforce さんのおっしゃる通り、だいたい `lib` 配下に置きます。

`bot_controller.rb` のイメージですが、以下のように必要なファイル `include` して **@bot** を引数に渡して取り回す、で合ってますかね？

```bot_controller.rb
require "./commands/xp_jpy"
include Commands

class Bot
  attr_accessor :word
  
  def initialize(word)
    @word = word
  end
end

@bot = Bot.new("convert xp2jpy")

xp_jpy(@bot)
```

```xp_jpy.rb
module Commands
  def xp_jpy(bot)
    puts bot.word
  end
end
```

`ruby bot_controller.rb`
=> convert xp2jpy

渡し方はもう少し改善できそうですが、うまく分割はできそうな気がしますね。

**Comment by harigel** [comment]
> コマンドモジュール等をincludeすると

メタプロ駆使してやってみようと思ったのですが複雑になりすぎて挫折しました:spaghetti:

もっとシンプルに、

```bot_controller.rb
# bot_controller.rb

class BotController
  def initialize()
    @bot = Discordrb::Commands::CommandBot.new token: ENV["TOKEN"], client_id: ENV["CLIENT_ID"], prefix: ["?", "？"]
  end

  def inject!(mod)
    if mod.respond_to? :inject_bot
      mod.inject_bot(@bot)
    end
  end

  def run
    @bot.run
  end
end
```

```how_many_people.rb
# how_many_people.rb

module HowManyPeople
  module_function
  def inject_bot(bot)
    bot.command [:今何人] do |event|
      event.respond "#{event.user.mention} <:xpchan01:391497596461645824>＜ ここには今#{event.server.member_count}人いるよ〜"
    end
  end
end
```

```rb
# 使い方

bc = BotController.new
bc.inject! HowManyPeople
bc.run
```

こんな感じがわかりやすくていいかなと。どうでしょうか。

**Comment by mc-chinju** [comment]
おお、[DI](https://qiita.com/hshimo/items/1136087e1c6e5c5b0d9f) ですね。
ruby ではさほど見ないのと、`@bot` を入れ替えることもないように思うので、ちょっと考えさせてください 🤔

**Comment by harigel** [comment]
DI…なんですかね？（よくわかってない
https://github.com/meew0/discordrb/blob/master/lib/discordrb/commands/container.rb#L90
雰囲気はdiscordrbのこのあたりを参考にしてます。

**Comment by mc-chinju** [comment]
参考ソースありがとうございます！
他の方がよければ、 @harigel さん提案の実装でいいと思いますー。

**Comment by harigel** [comment]
ありがとうございます。
discordrbにすでにある機能を使ってもうちょっといい感じに出来そうです。大鉈振るうので時間かかりますがちょっとやってみます。

**Comment by Asuforce** [comment]
僕も賛成です〜

**Comment by toshikidoi** [comment]
完全に出遅れましたが、方向性大賛成です〜〜！！

**Comment by harigel** [comment]
project作ってみました。
https://github.com/xpjp/xpfiat-bot/projects/2

まずはコマンドの分割をしてます、という感じで…

**Comment by Asuforce** [comment]
これ終わったら、TDD を進めたいお気持ちです

**Comment by Asuforce** [comment]
@harigel ありがとうございました 😊 
目標は達成されので、次はテストだ！
