### ISSUE TITLE
スキルマップ的なのを作る

### ISSUE THREAD

**Issue by rockymanobi** [xpjp/xpfiat-bot#7]
developmentチャネルで議論されてましたが誰が何を出来るのかというのは知れるようにしておいたほうがよさそう

という備忘録

**Comment by Diaboro87** [comment]
https://github.com/xpjp/xpfiat-bot/wiki/%E7%B0%A1%E6%98%93%E3%82%B9%E3%82%AD%E3%83%AB%E3%83%9E%E3%83%83%E3%83%97

とりあえず作りました。
ただ、他の人のところはわからんので、気が向いたら各自埋めといて下さい。
