### ISSUE TITLE
CI を導入する

### ISSUE THREAD

**Issue by Asuforce** [xpjp/xpfiat-bot#8]
### 概要

これからの発展にはコードの信用性を保証できる必要があると思います。
そのためにも、まずはバージョン確認くらいから CI を導入できると良さそうかなと思います。

### ゴール

- どの CI サービスを利用するか決める

**Comment by rockymanobi** [comment]
> まずはバージョン確認くらいから
スタートポイントとしてめっちゃいいすね

> サービス
個人的意見でしか無いですが、最近circle ci 使うことが多いので慣れてるのはあります
前はよくtravis使ってました
今流行とかあればそれでも良いと思います

**Comment by suzumi** [comment]
travisで良いかと思います

**Comment by toshikidoi** [comment]
> まずはバージョン確認くらいから

これくらいから始めるの賛成です！

> どの CI サービスを利用するか決める

最近はCircleCIばっかり使ってるので個人的に慣れてますが、別に拘りないので、Travis等、他の奴でも良いです〜。

**Comment by Asuforce** [comment]
僕も Travis でいいかなという気持ちです。 Travis の経験者が多いようなので、ひとまず Travis でやっていこうと思います。

**Comment by Asuforce** [comment]
導入終わったのでクローズ
