### ISSUE TITLE
降雨量コマンド(?how_rain)の処理および出力

### ISSUE THREAD

**Issue by serisia** [xpjp/xpfiat-bot#86]
### 実現したいこと

現行の実装だと、?how_rainの出力は、空rainを含んだ総量を出力しています。
コミュニティメンバーより、空rainを反映させない形で出力されるように修正して欲しいと依頼がありました。

### ゴール

空rainを含まない形で降雨量を算出し、メッセージとする

### 相談したいこと

方針として、
1. Xp-BotのRainedのメッセージの内容を蓄積する
　出力内容が従来の「rain総量」ではなく、「ユーザーあたりの降雨量」になる
　処理自体は単一のMessageを見て合算するだけなので、バグを生む可能性は低く、また
　現行の処理から大きく乖離しない
　（出力のうち、小数点以下の桁数については別途考慮が必要かもしれない）

2. rainコマンドと、その応答を見て算出する
　mentionはどの発言に対しての応答かが記録されないので、複数回rainコマンドをした場合、
　取得した範囲によっては誤った情報を出力する可能性がある
　（,rain 1000、,rain 5000、rained、ときて5000のrainの反応は遅延しているが、
　　100件取得に最初のrainが含まれない場合、5000のrainが成功したと解釈せざるをえない）
　副次効果として、Botの反応を待っているXPの量が取得できる
　（先行したpull requestはこちらで実装していた）

3. Xp-BotのRainedのメッセージの内容を蓄積しつつ、ユーザー数をかけて総量を算出する
　現行の出力と形式が変わらず、また空rainおよび未確定なrainを排除することができる
　ただし、ユーザーごとのXPは剰余が出ている可能性が高く、正確な値とならない可能性が高い
　（ログを見るに、整数で打っている場合が殆どなので、四捨五入するとほぼ揃うとは思う）

が考えられます。
個人的には「3はないかなぁ」と思っていますが、どのような形が良いと思われますか？
また、良い第4案があれば提示頂ければ。

**Comment by MaySoMusician** [comment]
rainごとに配られる対象のユーザーが異なる点を考えると、
方針1の拡張が良いと思います。

Xp-Botの応答は、
```
（絵文字略）メンション, Rained: 金額 To: 人数 Users Online. （絵文字略）
```
になるので、
方針1を使い、さらに正規表現で「金額」と「人数」を取得すれば、
従来のrain総量が返せると思います

端数に関しては、Game Balanceは小数点第七位まで表示されているので
小数点第八位あたりで四捨五入するのが妥当かと。

**Comment by serisia** [comment]
MaySoMusicianさん、回答ありがとうございます。
BotのRain応答メッセージごとに
　ユーザーあたりXP量 : A
　対象ユーザー数 : B
とした場合、A × B の値を算出、複数あれば合計し、総量とする、ということですね。
これを3として書いたつもりでしたが、書き方が悪かったようです。すみません。
「ユーザー数を掛けたもの蓄積し、総量を算出する」ですね。

3において、何を懸念しているかというと、
　,rain 300
　Rained: 0.23492560689115113 To : 1277 Users
だった場合、積は299.99999999999999301となります。（rubyで普通に計算するともっと丸まりましたが）
これが、ユーザー視点で気持ち悪くないのか？ということでした。
これをGameBalanceの仕様に基づき、7桁まで有効として四捨五入することで揃えれば、「rainしたXPが整数、あるいは桁数の少ない小数であれば」違和感のある結果になることはなさそうですし、有効桁数は根拠があり妥当です。

有効桁数についての実験として、退席中状態にしてrainを受けられないようにし、rainコマンドを打ってみました。
　,rain 100.00000009
　@serisia, Rained: 0.04618937648498845 To: 2165 Users Online.
という結果が得られました。
これは乗算すると100.00000008999999425となり、第8位の「9」が反映されていると見えます。
切り上げられているようには見えず、rainのコマンドは小数点以下7桁までではないようです。
前後でbalanceをとったところ、GameBalanceは
　36638.7526270 -> 36538.7526269
と、100.0000001減っていました。
切り上げられているのか、7桁より下もあるが表示されない仕様なのかについては、
10回以上やって毎回,balanceをすれば確認できるかもしれませんが、負荷になるうえ遅延が酷いのでやっていません。
（途中、誤差が蓄積するとwithdrawの際にXPの残高不足になる恐れがあるのでは？と思いましたが、実際は手数料でその分くらいは相殺できるでしょう）

?how_rainの結果の正確性について問題になること自体はほぼないと思いますので、「小数のrainをしたらたまに誤差がでる」前提で方針3を採用するとしても、特に問題ないとは思います。

他にも意見があれば、よろしくお願いします。

**Comment by serisia** [comment]
※時間があったのでひとまず手元で方針3での実装をしました。実際のBotの反応をいくつか投げたところ値は問題なさそうです。後ほど小数部のあるrainを何度かやってBotのレスポンスサンプルをとるつもり。

**Comment by Diaboro87** [comment]
このコマンドを作った私からすればとても雑に作っておいていい機能だと思っております。
それこそ、もともとの機能では、コマンドの時点から過去100件までのメッセージしか取得しておりません。
なので、小数点以下切り捨てとかでいいような気がします。
この対応ではあくまで「空レイン」を取り除くことを目標としているようなので、正確な値を出すことは別イシューとして行ってはいかがでしょうか？

**Comment by serisia** [comment]
「空rainを除外する」と「算出する値の正確性の向上」について別Issueとして考えるのですね。
値の正確性については追及する必要があるのか？ということになりますが、個人的には「ユーザーが違和感のない形で空rainを取り除ければ問題ない」と思いますので、今回の変更の結果もし誤差が気になるというリクエストがあれば別途Issueを立てるようにすればよいかと思っています。

本Issueでの実装方針として、MaySoMusicianさんはGameBalanceの表示桁数にそろえる、Ryo(Diaboro87)さんは整数部までで切り捨てる、というご意見です。
Ryoさんの意見を採用した場合、例えば300のrainをした際に?how_rainすると「299」と出力されるケースが多くなりますので、整数部だけとするのであっても、切り捨てではなく四捨五入とするのがよさそうだと感じます。
ひとまず、方針3（+小数点第8位を四捨五入）で実装し本件Close、もしリクエストが飛んでくれば再度Issueを作成して値について議論、としたいと思いますが、よいでしょうか？

**Comment by Diaboro87** [comment]
了解しました。それでいいと思います。

**Comment by Asuforce** [comment]
細かい話ですが PR がクローズされてから関連 issue をクローズすると良さそうです〜 👍

**Comment by serisia** [comment]
なるほど了解です、それまでオープンしておきます。
ぐちゃっとしてしまいます、すみません。
