### ISSUE TITLE
翻訳機能のデグレ？(要確認)

### ISSUE THREAD

**Issue by Diaboro87** [xpjp/xpfiat-bot#94]
https://github.com/xpjp/xpfiat-bot/blob/689cd312372a4d31c36eefadb597fa36ef0d59eb/lib/actions/commands/translate.rb#L20

文字列結合の際に、半角スペースも含めて結合するようにしていたが、半角スペースが取り除かれるようになっていた。

**Comment by mc-chinju** [comment]
んー、なんでですかね。処理自体は同じだと思うんですが 🤔 

```rb
irb(main):007:0> sentences = ["This", "is", "xp"]
=> ["This", "is", "xp"]
irb(main):008:0> sentences.join("")
=> "Thisisxp"
irb(main):009:0> sentences.join(" ")
=> "This is xp"
```

**Comment by Diaboro87** [comment]
あー、失礼。半角スペースで結合してたんですね。
確認不足でした。
クローズで。
