### ISSUE TITLE
円換算した数値を日本語表記にするgemを導入したい

### ISSUE THREAD

**Issue by mario2331** [xpjp/xpfiat-bot#96]
### 実現したいこと

時価総額botの動作確認をしていたところ、円換算すると桁数が多すぎて金額がわかりづらかった
ため、円換算した数値を日本語表記（○○億○○万○○円）に変更するgemを導入したいです。

### ゴール

https://github.com/siman-man/yen
このgemを導入する。

**Comment by mc-chinju** [comment]
最終的に https://github.com/ttanimichi/number_to_yen を導入
